# Generated by Django 3.1.14 on 2024-10-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241006_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intento1',
            old_name='txt',
            new_name='documento',
        ),
    ]
