# Generated by Django 3.1.14 on 2024-10-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241006_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='bbdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('documento1', models.FileField(upload_to='archivos/')),
                ('documento2', models.FileField(upload_to='archivos/')),
            ],
        ),
    ]
